<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="renwei-PC" name="com.aoyou.test.cases.BookingOrderService.VisaOrderReserve001" tests="2" failures="0" timestamp="14 Jan 2016 02:34:41 GMT" time="20.513" errors="2">
  <testcase name="visaOrderReserve001" time="10.249" classname="com.aoyou.test.cases.BookingOrderService.VisaOrderReserve001">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.aoyou.test.templates.orderservice.CancelOrder.setRequestData(CancelOrder.java:37)
	at com.aoyou.test.templates.WebSerivceTemplate.sendPost(WebSerivceTemplate.java:52)
	at com.aoyou.test.base.Action.CancelOrder(Action.java:107)
	at com.aoyou.test.cases.BookingOrderService.VisaOrderReserve001.visaOrderReserve001(VisaOrderReserve001.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:991)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1171)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- visaOrderReserve001 -->
  <testcase name="visaOrderReserve001" time="10.264" classname="com.aoyou.test.cases.BookingOrderService.VisaOrderReserve001">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.aoyou.test.templates.orderservice.CancelOrder.setRequestData(CancelOrder.java:37)
	at com.aoyou.test.templates.WebSerivceTemplate.sendPost(WebSerivceTemplate.java:52)
	at com.aoyou.test.base.Action.CancelOrder(Action.java:107)
	at com.aoyou.test.cases.BookingOrderService.VisaOrderReserve001.visaOrderReserve001(VisaOrderReserve001.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:991)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1171)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- visaOrderReserve001 -->
</testsuite> <!-- com.aoyou.test.cases.BookingOrderService.VisaOrderReserve001 -->
